service:
  server_port: "8090"
  address: "localhost"

database:
  host: "localhost"
  port: 5433
  username: "admin"
  password: "1234"
  name: "winter_db"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  ReadTimeout: 2s
  WriteTimeout: 2s